### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by halhenke** [nkbt/opera-github-sidebar#8]
Do you think you could rewrite this in typescript so that it is not irretrievably broken? 

Preferably by New Years? That would be super thanx!

![](https://media3.giphy.com/media/3o6nV52zqc8THWeWeA/giphy.gif)

**Comment by nkbt** [comment]
![24294200_1509494845772520_4815744207780232895_n](https://user-images.githubusercontent.com/175264/34330225-9102daba-e96d-11e7-81c5-ebf750661723.jpg)
